title: JaiMan NG
logo: /assets/images/DPhy-ENS.pdf
baseurl: "/portfolio" # Base URL for your site
url: "https://JimmyWhou.github.io" # Your GitHub Pages URL
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  math_engine_opts:
    extensions:
      - tex
    inline_delimiter: '\\('
    display_delimiter: '\\['
