title: JaiMan NG
logo: /assets/images/DPhy-ENS.pdf
baseurl: "/portfolio" # Base URL for your site
url: "https://JimmyWhou.github.io" # Your GitHub Pages URL
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM

quote: "You've gotta sing like no one is listening, love like you've never been hurt, dance like no one is watching, & live like it is heaven on earth."
